services:
  - type: web
    name: olympiad-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        value: 8808389966:AAEF2DVKDZ5uwZiJcLet6YuqsL08D_IOXg0
